#pragma once

// From
// https://github.com/pocoproject/poco/blob/7f7c2f5484ea57fc4023863a764c079d1f52651d/Foundation/include/Poco/UnWindows.h
// This is no longer in poco.
#undef GetBinaryType
#undef GetShortPathName
#undef GetLongPathName
#undef GetEnvironmentStrings
#undef SetEnvironmentStrings
#undef FreeEnvironmentStrings
#undef FormatMessage
#undef EncryptFile
#undef DecryptFile
#undef CreateMutex
#undef OpenMutex
#undef CreateEvent
#undef OpenEvent
#undef CreateSemaphore
#undef OpenSemaphore
#undef LoadLibrary
#undef GetModuleFileName
#undef CreateProcess
#undef GetCommandLine
#undef GetEnvironmentVariable
#undef SetEnvironmentVariable
#undef ExpandEnvironmentStrings
#undef OutputDebugString
#undef FindResource
#undef UpdateResource
#undef FindAtom
#undef AddAtom
#undef GetSystemDirectory
#undef GetTempPath
#undef GetTempFileName
#undef SetCurrentDirectory
#undef GetCurrentDirectory
#undef CreateDirectory
#undef RemoveDirectory
#undef CreateFile
#undef DeleteFile
#undef SearchPath
#undef CopyFile
#undef MoveFile
#undef ReplaceFile
#undef GetComputerName
#undef SetComputerName
#undef GetUserName
//#undef LogonUser
#undef GetVersion
#undef GetObject

// Further undefs not part of the poco set:
#undef LoadString
#undef FindResourceEx
#undef GetModuleHandle
#undef GetModuleHandleEx
#undef LoadLibraryEx
#undef EnumResourceLanguagesEx
#undef EnumResourceNamesEx
#undef EnumResourceTypesEx
#undef EnumResourceNames
#undef CreateDesktop
#undef CreateDesktopEx
#undef OpenDesktop
#undef GetMessage
#undef SendMessage
